import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./styles/globals.css";
import "@/public/icon/iconly.css";
import HeaderLayouts from "@/layout/HeaderLayouts";
import FooterLayout from "@/layout/FooterLayout";

const urbanist = Urbanist({
  variable : '--font-urbanist',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Shopking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} antialiased`}
      >
        <HeaderLayouts/>
           {children}
        <FooterLayout/>
      </body>
    </html>
  );
}
